### ISSUE TITLE
Filtering with hardware FIR

### ISSUE THREAD

**Issue by alalons** [xaelsouth/rtl-wmbus#16]
Hello Xael!
Reading [about RTL chips](http://www.pa3fwm.nl/technotes/tn20.html) there seems to be configurable FIR filters on hardware. Seems to me that would be useful to decrease CPU load.

"...Furthermore, the downsampling is configurable: how far the samplerate is lowered after the low-pass filter, which also determines the simultaneously receivable bandwidth. And part of the low-pass filter turns out to be a FIR filter with programmable coefficients, although this flexibility is not exploited by current driver software"

Just thinking loud

**Comment by xaelsouth** [comment]
Hello alalons!

Well, rtl_wmbus should be understood as a pipe filter only - it does not include anything hardware specific and is doing just nothing with underlying hardware. This job is done by rtl_sdr (for RTL SDR) or rx_sdr (for LimeSDR Mini and other hardware).  Downsampling is not a problem at all because it's implemented as an averaging filter, which is basically a simpler adder. After averaging every n-th sample will be dropped - that's all.

I will close the issue now.
