### ISSUE TITLE
Wmbus device , using different frequency and different transmission speed

### ISSUE THREAD

**Issue by jacksonlancaster** [xaelsouth/rtl-wmbus#46]
I have a wireless mbus device that uses 915MHz and 250kbps transmission rate. It sends data in C1 format. Since it's non standard freq and speed, how would I read this? Any parameters I can change or code I can modify to accommodate this?

I tried using this command, but it never decodes any data.
rtl_sdr -f 918.5M -s 2048k - 2>/dev/null | rtl_wmbus

**Comment by xaelsouth** [comment]
Hello jacksonlancaster.

The frequency does not matter, yet the transmission rate. 

ideally we want 8 samples per chip at 100kbps transmission rate. rtl_wmbus achieves this by sampling at 1.6M and then decimate the signal by the factor 2. 

Therefore, the sampling rate must be set to at least 2MHz if you have 250kbps transmission rate and you still need 8 samples per chip. You could do something this like this:
rtl_sdr -f 918.5M -s 2000000 - 2>/dev/null | rtl_wmbus -d 1

"-d 1" means there is no decimation applied to the sampled signal. But you have to recalculate all filter coefficients for the new sample rate, which in that case is 2MHz (instead of 800kHz) .
